### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by skyclo** [ideoxan/koala#1]
A README.md should be created for Koala (the ideoxan editor) that has the same format as [ideoxan/ideoxan](https://github.com/ideoxan/ideoxan)'s README.md to keep uniformity among the repositories.

**Comment by rajatRS** [comment]
Would you please assign me this task ? :)

**Comment by rajatRS** [comment]
Thank you 
Please make me clear that wether you want a readme file for " koala js " or ideoxan editor.

**Comment by skyclo** [comment]
> Thank you 
> Please make me clear that wether you want a readme file for " koala js " or ideoxan editor.

Ah sorry about that, branding is a little confusing. The nickname for the Ideoxan editor is Koala. So essentially a readme for this repository is what we are looking for. 

We already have a format for the server and website on our main repository (ideoxan/ideoxan) but not on this one yet.

Sorry for the confusion!

**Comment by rajatRS** [comment]
No problem, I'm heading forward to create a required readme.
