### ISSUE TITLE
Add Emmet Snippet completion in the editor

### ISSUE THREAD

**Issue by skyclo** [ideoxan/koala#2]
**Is your feature request related to a problem? Please describe.**
Emmet is a powerful tool for developers that allow for quick content creation. Using these snippets, people can create elements that would have taken a lot longer to make, structure and format.

**Describe the solution you'd like**
Emmet's features should be implemented into the Ideoxan editor to make developing a little bit easier.

**Additional context**
The Ace Editor (the library that powers the text editor) has an auto-completion feature built in. While it is really basic, it is possible for it to be customized.

**Comment by ArduinoidIOT** [comment]
Could I be assigned to this?

**Comment by skyclo** [comment]
> Could I be assigned to this?

Assigned!
